What is the capital of {stateOrCountry}? Responsd with only JSON format without any other text.
The JSON response should include a property of `stateOrCountry` that contains the name of the state or the country.
The JSON response should include a property of `capital` that contains the capital city name of the state or the country.
The JSON response should include a property of `population-in-mil` that containse the population number of the city in millions in decimal format.
The JSON response should include a property of `region` that contains where the city is located.
The JSON response should include a property of `language` that contains the primary language spoken in the city.
The JSON response should include a property of `curreny` that contains the currency used by the country or state.
The JSON response should include a property of `lat` that contains the city's latitude.
The JSON response should include a property of `lng` that contains the city's' longitude.
